# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  # Ansible Controller
  config.vm.define "ansible-controller" do |controller|
    controller.vm.hostname = "controller"
    controller.vm.network "private_network", ip: "192.168.33.100"

    # 🔁 Synchronisation du dossier local avec la VM
    controller.vm.synced_folder "./ansible-project", "/home/vagrant/ansible-project"

    controller.vm.provision "shell", inline: <<-SHELL
      apt update -y
      apt install -y ansible
    SHELL
  end

  # Web Host
  config.vm.define "web" do |web|
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.33.10"
  end

  # DB Host
  config.vm.define "db" do |db|
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.33.11"
  end
end

