---
- name: Install MariaDB on DB server
  hosts: dbservers
  become: true

  vars_files:
    - ../vars/db.yml

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MariaDB server
      apt:
        name: mariadb-server
        state: present

    - name: Install PyMySQL module for Ansible
      apt:
        name: python3-pymysql
        state: present

    - name: Start and enable MariaDB
      service:
        name: mariadb
        state: started
        enabled: true

    - name: Set root password (non-interactive)
      mysql_user:
        name: root
        password: "{{ mariadb_root_password }}"
        login_unix_socket: /run/mysqld/mysqld.sock
        host_all: true
        state: present

